---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-micro-pg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-micro-pg-app
  template:
    metadata:
      labels:
        app: go-micro-pg-app
    spec:
      containers:
        - name: go-micro-pg-app
          image: go-micro-pg
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
